name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install pyenv
        run: |
          curl https://pyenv.run | bash
          export PYENV_ROOT="$HOME/.pyenv"
          command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
          eval "$(pyenv init -)"

      - name: Install dependencies
        run: |
          python -m pip install pipenv
          pipenv install ruff --dev

      - name: Lint using Ruff
        run: |
          pipenv run ruff src/prometheus_salt_exporter/*.py
