name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install ruff

      - name: Lint using Ruff
        run: |
          ruff src/prometheus_salt_exporter/*.py
