---
name: Upload Python Package

# yamllint disable-line rule:truthy
on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install --yes python3-wheel twine

      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          python3 setup.py sdist bdist_wheel
          twine upload dist/*
      
      - name: Publish tar.gz
        uses: actions/upload-artifact@v3
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        path: dist/

  verify:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Verify installation
        run: |
          pip install prometheus-salt-exporter
